version: '3'

services:
  node:
    build:
      context: ./node
      args:
          - NODE_VERSION=${NODE_VERSION}
    ports:
      - "3000:3000"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    tty: true