.PHONY: build up start stop down status node

build:
	docker-compose build

up:
	docker-compose up -d

start:
	docker-compose start

stop:
	docker-compose stop

down:
	docker-compose down

status:
	docker-compose ps

node:
	docker-compose exec node /bin/sh